### ISSUE TITLE
Create explainations on README.md

### ISSUE THREAD

**Issue by gmelodie** [LTKills/parallel-programming#2]
Create brief explainations for each topic (pthreads, openmp, openmpi)

e.g: 
## Pthreads
Pthreads, or Posix Threads, are a standard of....

**Comment by preeti98** [comment]
May I please work on this issue? I have no prior experience  with these terms, so I referred to wikipedia and got some information on the same.

**Comment by gmelodie** [comment]
Sure! feel free to ask me any doubts you might have :)
